/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladorderedes.visao;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Júlio Campos
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    public void inserirDesktop() {
        ImageIcon desktop = new ImageIcon(getClass().getResource("/imagens/desktop.png"));
        jLabelDesktop1.setIcon(desktop);
        jLabelDesktop2.setIcon(desktop);
        jLabelDesktop3.setIcon(desktop);
    }

    public void inserirServidor() {
        ImageIcon servidor = new ImageIcon(getClass().getResource("/imagens/servidor.png"));
        jLabelServidor.setIcon(servidor);
    }

    public void inserirSwitch() {
        ImageIcon comutador = new ImageIcon(getClass().getResource("/imagens/switch.png"));
        jLabelSwitch.setIcon(comutador);
    }

    public void inserirRoteador() {
        ImageIcon roteador = new ImageIcon(getClass().getResource("/imagens/roteador.png"));
        jLabelRoteador.setIcon(roteador);
    }

    public void realizarConexao() {
        ImageIcon internet = new ImageIcon(getClass().getResource("/imagens/internet.png"));
        jLabelInternet.setIcon(internet);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonDesktop = new javax.swing.JButton();
        jButtonServidor = new javax.swing.JButton();
        jButtonRoteador = new javax.swing.JButton();
        jButtonSwitch = new javax.swing.JButton();
        jButtonConectar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonHub1 = new javax.swing.JButton();
        jLabelDesktop3 = new javax.swing.JLabel();
        LogInternalFrame = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jLabelServidor = new javax.swing.JLabel();
        jLabelDesktop1 = new javax.swing.JLabel();
        jLabelDesktop2 = new javax.swing.JLabel();
        jLabelSwitch = new javax.swing.JLabel();
        jLabelInternet = new javax.swing.JLabel();
        jLabelRoteador = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuNovo = new javax.swing.JMenuItem();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuSalvar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuDesfazer = new javax.swing.JMenuItem();
        jMenuRefazer = new javax.swing.JMenuItem();
        abaPlay = new javax.swing.JMenu();
        jMenuConectar = new javax.swing.JMenuItem();
        jMenuEnviarMensagem = new javax.swing.JMenuItem();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuPreferencias = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Rede");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButtonDesktop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/desktop.png"))); // NOI18N
        jButtonDesktop.setToolTipText("");
        jButtonDesktop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesktopActionPerformed(evt);
            }
        });

        jButtonServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/servidor.png"))); // NOI18N
        jButtonServidor.setMaximumSize(new java.awt.Dimension(120, 120));
        jButtonServidor.setMinimumSize(new java.awt.Dimension(120, 120));
        jButtonServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServidorActionPerformed(evt);
            }
        });

        jButtonRoteador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/roteador.png"))); // NOI18N
        jButtonRoteador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoteadorActionPerformed(evt);
            }
        });

        jButtonSwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/switch.png"))); // NOI18N
        jButtonSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSwitchActionPerformed(evt);
            }
        });

        jButtonConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/conexao.png"))); // NOI18N
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        jButtonHub1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hub.png"))); // NOI18N
        jButtonHub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHub1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonRoteador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonHub1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRoteador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHub1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1024, 190));

        jLabelDesktop3.setText("Desktop 3");
        jLabelDesktop3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDesktop3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDesktop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 80, 80));

        LogInternalFrame.setBorder(null);
        LogInternalFrame.setClosable(true);
        LogInternalFrame.setTitle("Logs");
        LogInternalFrame.setVisible(true);

        TextArea1.setBackground(new java.awt.Color(0, 0, 0));
        TextArea1.setColumns(20);
        TextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        TextArea1.setRows(5);
        TextArea1.setToolTipText("");
        jScrollPane1.setViewportView(TextArea1);

        javax.swing.GroupLayout LogInternalFrameLayout = new javax.swing.GroupLayout(LogInternalFrame.getContentPane());
        LogInternalFrame.getContentPane().setLayout(LogInternalFrameLayout);
        LogInternalFrameLayout.setHorizontalGroup(
            LogInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        LogInternalFrameLayout.setVerticalGroup(
            LogInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInternalFrameLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(LogInternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 24, -1, -1));

        jLabelServidor.setText("Servidor");
        jLabelServidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelServidorMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 80, 80));

        jLabelDesktop1.setText("Desktop 1");
        jLabelDesktop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDesktop1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDesktop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 80, 80));

        jLabelDesktop2.setText("Desktop 2");
        jLabelDesktop2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDesktop2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDesktop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 80, 80));

        jLabelSwitch.setText("Switch");
        jLabelSwitch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSwitchMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelSwitch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 80, 80));

        jLabelInternet.setText("Internet");
        jLabelInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInternetMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 80, 80));

        jLabelRoteador.setText("Roteador");
        jLabelRoteador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRoteadorMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRoteador, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 80, 80));

        jMenuArquivo.setText("Arquivo");

        jMenuNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/new.png"))); // NOI18N
        jMenuNovo.setText("Novo");
        jMenuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuNovo);

        jMenuAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/open.png"))); // NOI18N
        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuAbrir);

        jMenuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/save.png"))); // NOI18N
        jMenuSalvar.setText("Salvar");
        jMenuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalvarActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuSalvar);
        jMenuArquivo.add(jSeparator1);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/exit.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuSair);

        MenuPrincipal.add(jMenuArquivo);

        jMenuEditar.setText("Editar");

        jMenuDesfazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/undo.png"))); // NOI18N
        jMenuDesfazer.setText("Desfazer");
        jMenuDesfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDesfazerActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuDesfazer);

        jMenuRefazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/redo.png"))); // NOI18N
        jMenuRefazer.setText("Refazer");
        jMenuEditar.add(jMenuRefazer);

        MenuPrincipal.add(jMenuEditar);

        abaPlay.setText("Executar");

        jMenuConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/link.png"))); // NOI18N
        jMenuConectar.setText("Conectar dispositivos");
        jMenuConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConectarActionPerformed(evt);
            }
        });
        abaPlay.add(jMenuConectar);

        jMenuEnviarMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/email.png"))); // NOI18N
        jMenuEnviarMensagem.setText("Enviar mensagem");
        jMenuEnviarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEnviarMensagemActionPerformed(evt);
            }
        });
        abaPlay.add(jMenuEnviarMensagem);

        MenuPrincipal.add(abaPlay);

        jMenuOpcoes.setText("Opções");

        jMenuPreferencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/config.png"))); // NOI18N
        jMenuPreferencias.setText("Preferências");
        jMenuOpcoes.add(jMenuPreferencias);

        MenuPrincipal.add(jMenuOpcoes);

        jMenuAjuda.setText("Ajuda");

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/info.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuAjuda.add(jMenuSobre);

        MenuPrincipal.add(jMenuAjuda);

        setJMenuBar(MenuPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuNovoActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    private void jMenuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSalvarActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuDesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDesfazerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuDesfazerActionPerformed

    private void jMenuConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuConectarActionPerformed

    private void jMenuEnviarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEnviarMensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEnviarMensagemActionPerformed

    private void jButtonDesktopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesktopActionPerformed
        inserirDesktop();
    }//GEN-LAST:event_jButtonDesktopActionPerformed

    private void jButtonServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServidorActionPerformed
        inserirServidor();
    }//GEN-LAST:event_jButtonServidorActionPerformed

    private void jButtonRoteadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoteadorActionPerformed
        inserirRoteador();
    }//GEN-LAST:event_jButtonRoteadorActionPerformed

    private void jButtonSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSwitchActionPerformed
        inserirSwitch();
    }//GEN-LAST:event_jButtonSwitchActionPerformed

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        realizarConexao();
    }//GEN-LAST:event_jButtonConectarActionPerformed


    private void jLabelDesktop3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDesktop3MouseClicked
        ConfigDesktop frame = new ConfigDesktop();
        frame.setVisible(true);
    }//GEN-LAST:event_jLabelDesktop3MouseClicked

    private void jLabelServidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelServidorMouseClicked
        ConfigServidor frame = new ConfigServidor();
        frame.setVisible(true);
    }//GEN-LAST:event_jLabelServidorMouseClicked

    private void jLabelDesktop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDesktop1MouseClicked
        ConfigDesktop frame = new ConfigDesktop();
        frame.setVisible(true);
    }//GEN-LAST:event_jLabelDesktop1MouseClicked

    private void jLabelDesktop2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDesktop2MouseClicked
        ConfigDesktop frame = new ConfigDesktop();
        frame.setVisible(true);
    }//GEN-LAST:event_jLabelDesktop2MouseClicked

    private void jLabelSwitchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSwitchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSwitchMouseClicked

    private void jLabelInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInternetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelInternetMouseClicked

    private void jButtonHub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHub1ActionPerformed

    private void jLabelRoteadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRoteadorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelRoteadorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame LogInternalFrame;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JMenu abaPlay;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonDesktop;
    private javax.swing.JButton jButtonHub1;
    private javax.swing.JButton jButtonRoteador;
    private javax.swing.JButton jButtonServidor;
    private javax.swing.JButton jButtonSwitch;
    private javax.swing.JLabel jLabelDesktop1;
    private javax.swing.JLabel jLabelDesktop2;
    private javax.swing.JLabel jLabelDesktop3;
    private javax.swing.JLabel jLabelInternet;
    private javax.swing.JLabel jLabelRoteador;
    private javax.swing.JLabel jLabelServidor;
    private javax.swing.JLabel jLabelSwitch;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuItem jMenuConectar;
    private javax.swing.JMenuItem jMenuDesfazer;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuEnviarMensagem;
    private javax.swing.JMenuItem jMenuNovo;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JMenuItem jMenuPreferencias;
    private javax.swing.JMenuItem jMenuRefazer;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuSalvar;
    private javax.swing.JMenuItem jMenuSobre;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
